### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by noisegul** [finanalyst/pod-cached#14]
**Steps to reproduce:**
- Download and install Rakudo Star [2019.03](https://rakudo.org/files)
- `zef upgrade`
- `zef update`
- `zef install Pod::Cached`
```
===> Searching for: Pod::Cached
No candidates found matching identity: Pod::Cached
```
- `git clone https://github.com/finanalyst/pod-cached`
- `zef install ./pod-cached`

**Error output:**

```
> zef install ./pod-cached/
===> Testing: Pod::To::Cached:ver<0.3.0>
# Failed test 'doc cache created with sub-directories'
# at t\030-sub-directories.t line 25
# $!path has corrupt doc-cache
Cannot look up attributes in a Pod::To::Cached type object
  in method update-cache at C:\Users\tester\perl6\pod-cached\lib\Pod\To\Cached.pm6 (Pod::To::Cached) line 240
  in block <unit> at t\030-sub-directories.t line 26

# test pod extraction
$!path has corrupt doc-cache
  in submethod TWEAK at C:\Users\tester\perl6\pod-cached\lib\Pod\To\Cached.pm6 (Pod::To::Cached) line 146
  in block <unit> at t\040-pod-extraction.t line 16

# Heavy duty test optional
Aborting due to test failure: Pod::To::Cached:ver<0.3.0> (use --force-test to override)
===> Testing [FAIL]: Pod::To::Cached:ver<0.3.0>
```

**Desktop:**
 - OS: Windows 10 x64
 - Version 10.0.18362
 - Rakudo Star 2019.03

**Related issue:**
- https://github.com/antoniogamiz/Perl6-Documentable/issues/54

**Comment by finanalyst** [comment]
Can someone verify that this is a Windows only issue, or is it a Linux problem as well.

**Comment by noisegul** [comment]
For me it works on Linux and OSX.

Tested with:
* Linux: Rakudo Star 2019.03, built myself
* OSX: Rakudo Star 2019.03, installed via Homebrew

Would probably also be good if someone could confirm the installation error on Windows, since Windows is not my main workstation.

**Comment by finanalyst** [comment]
I had problems with an Ubuntu setup.
zef was not seeing `Pod::To::Cached`.
I have updated zef from 0.7.1 to current 0.7.4:
```
cd ~/zef    # the location Rakudo Star puts zef
git pull
perl6 -i. bin/zef install .
### to install P::Documentable
cd ~/development/perl6-documentable    ## where I have my local repo copy
zef install .
```
The installation proceeded to completion, and seemed to run the tests without a problem (?)
Next time I tried to install, it failed the tests.

However, the failures are not related to Pod::To::Cached

**Comment by finanalyst** [comment]
So far as I can discover, the Windows OS testing is initiated by zef (it is the only Module in the chain that has an appveyor configuration file).
There was an issue with Pod::To::Cached related to a change in JSON::Fast . This means that version required by Pod::To::Cached must be greater than JSON::Fast:ver<0.9.18> This is now fixed in the META.json file of P2Cached. 
zef is now installing the new version of Pod::To::Cached.
I am closing this issue for the time being. If a Windows issue reappears, then please renew the issue.

**Comment by JJ** [comment]
This issue is apparently still an issue, according to @noisegul . Can you all please check if there's still a problem and close it again if it's not?

**Comment by noisegul** [comment]
I gave it another go, issue persists as mentioned, same error output as above.
